### PR TITLE
fix(android): workaround for `Java heap space` when patching CLI

### LINKED ISSUE #738: CI: Gradle tests fail on Windows CI with `Java heap space`
### What happened?

Gradle tests fail on Windows CI due to running out of memory:

```
FAILURE: Build failed with an exception.

* Where:
Script 'D:\a\react-native-test-app\react-native-test-app\.android-test-TestAppUtilTest\node_modules\react-native-test-app\test-app.gradle' line: 41

* What went wrong:
A problem occurred evaluating script.
> Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

### Version

trunk

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
n/a
```

### Steps to Reproduce

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tido64**
### Description

Patching `@react-native-community/cli-platform-android` inline causes Gradle to run out of heap space.

Resolves #738

### Platforms affected

- [x] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### Test plan

I have a consistent repro in an internal repo, running:

```
rm -rf ~/.gradle
git clean -dfqx
./gradlew clean build
```

### CODE REVIEW

File: scripts/patch-cli-platform-android.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    path.dirname(
+      require.resolve(
+        "@react-native-community/cli-platform-android/package.json"
+      )
+    ),
+    "native_modules.gradle"
+  );
+
+  const script = fs.readFileSync(nativeModulesScript, { encoding: "utf-8" });
+  const patched = script.replace(
```
Comment (kelset) [inline scripts/patch-cli-platform-android.js:21]: maybe add the reference to why the patch here too?
```suggestion
  // TODO: Remove when `@react-native-community/cli` 6.0+ is required. See also
  // https://github.com/react-native-community/cli/commit/fa0d09b2c9be144bbdff526bb14f171d7ddca88e
  const patched = script.replace(
```

**Review by kelset — APPROVED** [review]
