### PR TITLE
fix(Apple): Also create an xcscheme to match app name

### LINKED ISSUE #239: Apple: Name the scheme something other than "ReactTestApp"
This came up as a minor detail in one of my PR's (https://github.com/microsoft/fluentui-react-native/pull/529/files#r509388900) that we must use the scheme name and have no control over it. In my scenario, we were adding steps in our build pipeline to build our test app for the purpose of packaging some native dependencies. In our yml, we had to use "ReactTestApp" instead of something more specific to our project, like "FURNTestApp". 

Minor detail, and definitely does not block anything =)

### PR DESCRIPTION
**Pull request by tido64**
Resolves #239

### CODE REVIEW

File: ios/test_app.rb [hunk 1]
```diff
@@ -201,10 +214,15 @@ def make_project!(xcodeproj, project_root, target_platform)
...
-  FileUtils.cp(File.join(src_xcodeproj, 'project.pbxproj'), dst_xcodeproj)
-  FileUtils.ln_sf(File.join(src_xcodeproj, 'xcshareddata'), dst_xcodeproj)
+  # Copy Xcode project files
+  FileUtils.mkdir_p(destination)
+  FileUtils.cp_r(src_xcodeproj, destination)
+  name, _display_name = app_name(project_root)
+  unless name.nil?
+    xcschemes_path = File.join(dst_xcodeproj, 'xcshareddata', 'xcschemes')
+    FileUtils.cp(File.join(xcschemes_path, 'ReactTestApp.xcscheme'),
+                 File.join(xcschemes_path, "#{name}.xcscheme"))
```
Comment (tido64) [inline ios/test_app.rb:224]: @Saadnajmi: Would this be enough? It just creates a copy of the scheme. Doesn't change the installed app name or anything. We could address that in a separate PR if desired.

Comment (Saadnajmi) [reply ios/test_app.rb:224]: @anandrajeswaran since he's the one who suggested it

Does that mean that there is 2 identical schemes now? ReactTestApp and <app name> ?

Comment (anandrajeswaran) [reply ios/test_app.rb:224]: SHouldn't it just create one scheme that is the {name} of the app?

Comment (tido64) [reply ios/test_app.rb:224]: I'm contemplating whether to keep `ReactTestApp` to be backwards compatible. It doesn't hurt, I think. And we can remove it in a later version.

Comment (Saadnajmi) [reply ios/test_app.rb:224]: That's fine by me to not have breaking changes. Thanks for actually implementing the feature request!

**Review by alloy — APPROVED** [review]
LGTM 👍
