### PR TITLE
fix(windows): wildcards in project items are not supported

### LINKED ISSUE #484: Windows: Wildcards in project items are not supported in VC projects
### What happened?

Assets are not visible in the solution and we're also getting this error message when opening the project: `D:\react-native-test-app\example\node_modules\.generated\windows\ReactTestApp\ReactTestApp.vcxproj : warning  : Wildcards in project items are not supported in VC projects and can cause unexpected behavior, instability and performance degradation in the Visual Studio IDE. Please refer to https://aka.ms/cpp/projectwildcards for supported options.`

### Version

0.7.6

### What platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
System:
    OS: Windows 10 10.0.19043
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 107.32 GB / 127.86 GB
  Binaries:
    Node: 14.17.5 - ~\AppData\Local\Temp\yarn--1631267329010-0.5985911790843006\node.CMD
    Yarn: 1.22.11 - ~\AppData\Local\Temp\yarn--1631267329010-0.5985911790843006\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31624.102 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.2 => 0.64.2
    react-native-windows: ^0.64.11 => 0.64.17
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

```
cd example
yarn
yarn install-windows-test-app --use-nuget
start windows\Example.sln
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tido64**
### Description

It doesn't look like wildcards are properly supported in Visual Studio. Converted to generating entries for all resources.

Resolves #484.

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [x] Windows

### Test plan

1. Test app should work with dev server:
   ```
   yarn install-windows-test-app --use-nuget
   yarn windows
   ```
2. Test app should work with JS bundle, without dev server:
   ```
   # terminate dev server
   yarn build:windows
   yarn install-windows-test-app --use-nuget
   yarn windows
   ```

`Assets` used to be empty before, but should be populated properly now:
Screenshot 2021-10-11 132125

### CODE REVIEW

File: windows/test-app.js [hunk 1]
```diff
@@ -196,34 +327,41 @@ function copyAndReplace(
...
-      ),
-      {
-        encoding: "utf-8",
-        mode: fs.statSync(srcPath).mode,
-      },
-      callback
-    );
+    // Treat as text file
+    fs.readFile(srcPath, textFileReadOptions, (err, data) => {
+      rethrow(err);
```
Comment (afoxman) [inline windows/test-app.js]: Seems like this `rethrow` should instead be `callback` followed by a return to skip the write.

**Review by afoxman — APPROVED** [review]
