### PR TITLE
fix(macOS): RCTRootView.minimumSize doesn't exist before 0.63

### LINKED ISSUE #268: error: value of type 'RCTRootView' has no member 'minimumSize'
### Description

`-[RCTRootView minimumSize]` wasn't added until [0.63](https://github.com/facebook/react-native/commit/432868b0c0c591c245a9cdb91201c64aa5bd70c6):

```
/Users/runner/work/async-storage/async-storage/node_modules/.generated/macos/ReactTestApp/AppDelegate.swift:155:26: error: value of type 'RCTRootView' has no member 'minimumSize'
                rootView.minimumSize = WindowSize.modalSize
                ~~~~~~~~ ^~~~~~~~~~~
```

### Your environment

* `react-native-test-app` version: 0.3.8
* Tested platforms:
  * [ ] Android
  * [ ] iOS
  * [x] macOS
  * [ ] Windows

### Steps to reproduce

1. `yarn set-react-version 0.62`
2. Build Example app for macOS

### PR DESCRIPTION
**Pull request by tido64**
### Description

`-[RCTRootView minimumSize]` wasn't added until [0.63](https://github.com/facebook/react-native/commit/432868b0c0c591c245a9cdb91201c64aa5bd70c6):

```
/Users/runner/work/async-storage/async-storage/node_modules/.generated/macos/ReactTestApp/AppDelegate.swift:155:26: error: value of type 'RCTRootView' has no member 'minimumSize'
                rootView.minimumSize = WindowSize.modalSize
                ~~~~~~~~ ^~~~~~~~~~~
```

Instead, we will set the frame size when the view is presented.

Resolves #268.

### Platforms affected

- [ ] Android
- [ ] iOS
- [x] macOS
- [ ] Windows

### Test plan

1. `yarn set-react-version 0.62`
2. Build Example app
3. Open Example app and make sure "App (modal)" works
4. `yarn set-react-version 0.63`
5. Repeat steps 2-3

### CODE REVIEW

File: macos/ReactTestApp/AppDelegate.swift [hunk 1]
```diff
@@ -150,9 +150,19 @@ final class AppDelegate: NSObject, NSApplicationDelegate {
 
         switch component.presentationStyle {
         case "modal":
-            viewController.view.frame = NSRect(size: WindowSize.modalSize)
+            let modalFrame = NSRect(size: WindowSize.modalSize)
+            viewController.view.frame = modalFrame
             if let rootView = viewController.view as? RCTRootView {
-                rootView.minimumSize = WindowSize.modalSize
+                var token: NSObjectProtocol?
```
Comment (tom-un) [inline macos/ReactTestApp/AppDelegate.swift:156]: Should it be a `let` and assign on same line?   Or, actually, if its not used don't need to assign token at all?

Comment (tido64) [reply macos/ReactTestApp/AppDelegate.swift:156]: It gets captured so we can unsubscribe on line 163.

Comment (tom-un) [reply macos/ReactTestApp/AppDelegate.swift:156]: Got it, somehow missed that

**Review by tom-un — APPROVED** [review]
